import Head from "next/head";
// import Image from "next/image";

import { withAuthenticator, AmplifySignOut } from "@aws-amplify/ui-react";

function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div>
				<header>
					<h1>We now have Auth!</h1>
				</header>
				<AmplifySignOut />
			</div>
		</div>
	);
}

export default withAuthenticator(Home);
